# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_auto_20170715_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
