# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0005_remove_postmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
