# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0008_auto_20170722_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
