# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0009_auto_20170722_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(max_length=250),
        ),
    ]
