# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0010_auto_20170722_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
