# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0013_remove_postmodel_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='postmodel',
            name='caption',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
    ]
