# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0014_auto_20170722_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='cartegory',
            field=models.CharField(default='', max_length=555),
            preserve_default=False,
        ),
    ]
