# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0015_postmodel_cartegory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='cartegory',
        ),
    ]
