# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0017_categorymodel_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='instaclone.UserModel'),
            preserve_default=False,
        ),
    ]
